// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-lbry/internal/db"
	"go.lumeweb.com/queryutil"
)

// NewMockDeviceService creates a new instance of MockDeviceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceService {
	mock := &MockDeviceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeviceService is an autogenerated mock type for the DeviceService type
type MockDeviceService struct {
	mock.Mock
}

type MockDeviceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceService) EXPECT() *MockDeviceService_Expecter {
	return &MockDeviceService_Expecter{mock: &_m.Mock}
}

// CreateDevice provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) CreateDevice(ctx context.Context, userID uint, name string, ipAddress string) (*db.Device, error) {
	ret := _mock.Called(ctx, userID, name, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for CreateDevice")
	}

	var r0 *db.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, string) (*db.Device, error)); ok {
		return returnFunc(ctx, userID, name, ipAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, string) *db.Device); ok {
		r0 = returnFunc(ctx, userID, name, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string, string) error); ok {
		r1 = returnFunc(ctx, userID, name, ipAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceService_CreateDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDevice'
type MockDeviceService_CreateDevice_Call struct {
	*mock.Call
}

// CreateDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - name string
//   - ipAddress string
func (_e *MockDeviceService_Expecter) CreateDevice(ctx interface{}, userID interface{}, name interface{}, ipAddress interface{}) *MockDeviceService_CreateDevice_Call {
	return &MockDeviceService_CreateDevice_Call{Call: _e.mock.On("CreateDevice", ctx, userID, name, ipAddress)}
}

func (_c *MockDeviceService_CreateDevice_Call) Run(run func(ctx context.Context, userID uint, name string, ipAddress string)) *MockDeviceService_CreateDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDeviceService_CreateDevice_Call) Return(device *db.Device, err error) *MockDeviceService_CreateDevice_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockDeviceService_CreateDevice_Call) RunAndReturn(run func(ctx context.Context, userID uint, name string, ipAddress string) (*db.Device, error)) *MockDeviceService_CreateDevice_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDevice provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) DeleteDevice(ctx context.Context, userID uint, id uint) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDevice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceService_DeleteDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDevice'
type MockDeviceService_DeleteDevice_Call struct {
	*mock.Call
}

// DeleteDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - id uint
func (_e *MockDeviceService_Expecter) DeleteDevice(ctx interface{}, userID interface{}, id interface{}) *MockDeviceService_DeleteDevice_Call {
	return &MockDeviceService_DeleteDevice_Call{Call: _e.mock.On("DeleteDevice", ctx, userID, id)}
}

func (_c *MockDeviceService_DeleteDevice_Call) Run(run func(ctx context.Context, userID uint, id uint)) *MockDeviceService_DeleteDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeviceService_DeleteDevice_Call) Return(err error) *MockDeviceService_DeleteDevice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceService_DeleteDevice_Call) RunAndReturn(run func(ctx context.Context, userID uint, id uint) error) *MockDeviceService_DeleteDevice_Call {
	_c.Call.Return(run)
	return _c
}

// GetDevice provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) GetDevice(ctx context.Context, userID uint, id uint) (*db.Device, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDevice")
	}

	var r0 *db.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) (*db.Device, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) *db.Device); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceService_GetDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDevice'
type MockDeviceService_GetDevice_Call struct {
	*mock.Call
}

// GetDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - id uint
func (_e *MockDeviceService_Expecter) GetDevice(ctx interface{}, userID interface{}, id interface{}) *MockDeviceService_GetDevice_Call {
	return &MockDeviceService_GetDevice_Call{Call: _e.mock.On("GetDevice", ctx, userID, id)}
}

func (_c *MockDeviceService_GetDevice_Call) Run(run func(ctx context.Context, userID uint, id uint)) *MockDeviceService_GetDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeviceService_GetDevice_Call) Return(device *db.Device, err error) *MockDeviceService_GetDevice_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockDeviceService_GetDevice_Call) RunAndReturn(run func(ctx context.Context, userID uint, id uint) (*db.Device, error)) *MockDeviceService_GetDevice_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeviceByIPAddress provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) GetDeviceByIPAddress(ctx context.Context, ipAddress string) (*db.Device, error) {
	ret := _mock.Called(ctx, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetDeviceByIPAddress")
	}

	var r0 *db.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*db.Device, error)); ok {
		return returnFunc(ctx, ipAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *db.Device); ok {
		r0 = returnFunc(ctx, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ipAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceService_GetDeviceByIPAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeviceByIPAddress'
type MockDeviceService_GetDeviceByIPAddress_Call struct {
	*mock.Call
}

// GetDeviceByIPAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - ipAddress string
func (_e *MockDeviceService_Expecter) GetDeviceByIPAddress(ctx interface{}, ipAddress interface{}) *MockDeviceService_GetDeviceByIPAddress_Call {
	return &MockDeviceService_GetDeviceByIPAddress_Call{Call: _e.mock.On("GetDeviceByIPAddress", ctx, ipAddress)}
}

func (_c *MockDeviceService_GetDeviceByIPAddress_Call) Run(run func(ctx context.Context, ipAddress string)) *MockDeviceService_GetDeviceByIPAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceService_GetDeviceByIPAddress_Call) Return(device *db.Device, err error) *MockDeviceService_GetDeviceByIPAddress_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockDeviceService_GetDeviceByIPAddress_Call) RunAndReturn(run func(ctx context.Context, ipAddress string) (*db.Device, error)) *MockDeviceService_GetDeviceByIPAddress_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDeviceService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockDeviceService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockDeviceService_Expecter) ID() *MockDeviceService_ID_Call {
	return &MockDeviceService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockDeviceService_ID_Call) Run(run func()) *MockDeviceService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceService_ID_Call) Return(s string) *MockDeviceService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDeviceService_ID_Call) RunAndReturn(run func() string) *MockDeviceService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ListDevices provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) ListDevices(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*db.Device, int64, error) {
	ret := _mock.Called(ctx, userID, filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListDevices")
	}

	var r0 []*db.Device
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) ([]*db.Device, int64, error)); ok {
		return returnFunc(ctx, userID, filters, sorts, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) []*db.Device); ok {
		r0 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*db.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockDeviceService_ListDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDevices'
type MockDeviceService_ListDevices_Call struct {
	*mock.Call
}

// ListDevices is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - filters []queryutil.CrudFilter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockDeviceService_Expecter) ListDevices(ctx interface{}, userID interface{}, filters interface{}, sorts interface{}, pagination interface{}) *MockDeviceService_ListDevices_Call {
	return &MockDeviceService_ListDevices_Call{Call: _e.mock.On("ListDevices", ctx, userID, filters, sorts, pagination)}
}

func (_c *MockDeviceService_ListDevices_Call) Run(run func(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockDeviceService_ListDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 []queryutil.CrudFilter
		if args[2] != nil {
			arg2 = args[2].([]queryutil.CrudFilter)
		}
		var arg3 []queryutil.Sort
		if args[3] != nil {
			arg3 = args[3].([]queryutil.Sort)
		}
		var arg4 queryutil.Pagination
		if args[4] != nil {
			arg4 = args[4].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockDeviceService_ListDevices_Call) Return(devices []*db.Device, n int64, err error) *MockDeviceService_ListDevices_Call {
	_c.Call.Return(devices, n, err)
	return _c
}

func (_c *MockDeviceService_ListDevices_Call) RunAndReturn(run func(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*db.Device, int64, error)) *MockDeviceService_ListDevices_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDevice provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) UpdateDevice(ctx context.Context, userID uint, id uint, name string, ipAddress string) (*db.Device, error) {
	ret := _mock.Called(ctx, userID, id, name, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDevice")
	}

	var r0 *db.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, string, string) (*db.Device, error)); ok {
		return returnFunc(ctx, userID, id, name, ipAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, string, string) *db.Device); ok {
		r0 = returnFunc(ctx, userID, id, name, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint, string, string) error); ok {
		r1 = returnFunc(ctx, userID, id, name, ipAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceService_UpdateDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDevice'
type MockDeviceService_UpdateDevice_Call struct {
	*mock.Call
}

// UpdateDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - id uint
//   - name string
//   - ipAddress string
func (_e *MockDeviceService_Expecter) UpdateDevice(ctx interface{}, userID interface{}, id interface{}, name interface{}, ipAddress interface{}) *MockDeviceService_UpdateDevice_Call {
	return &MockDeviceService_UpdateDevice_Call{Call: _e.mock.On("UpdateDevice", ctx, userID, id, name, ipAddress)}
}

func (_c *MockDeviceService_UpdateDevice_Call) Run(run func(ctx context.Context, userID uint, id uint, name string, ipAddress string)) *MockDeviceService_UpdateDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockDeviceService_UpdateDevice_Call) Return(device *db.Device, err error) *MockDeviceService_UpdateDevice_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockDeviceService_UpdateDevice_Call) RunAndReturn(run func(ctx context.Context, userID uint, id uint, name string, ipAddress string) (*db.Device, error)) *MockDeviceService_UpdateDevice_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDeviceName provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) UpdateDeviceName(ctx context.Context, userID uint, id uint, name string) (*db.Device, error) {
	ret := _mock.Called(ctx, userID, id, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDeviceName")
	}

	var r0 *db.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, string) (*db.Device, error)); ok {
		return returnFunc(ctx, userID, id, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, string) *db.Device); ok {
		r0 = returnFunc(ctx, userID, id, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint, string) error); ok {
		r1 = returnFunc(ctx, userID, id, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceService_UpdateDeviceName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDeviceName'
type MockDeviceService_UpdateDeviceName_Call struct {
	*mock.Call
}

// UpdateDeviceName is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - id uint
//   - name string
func (_e *MockDeviceService_Expecter) UpdateDeviceName(ctx interface{}, userID interface{}, id interface{}, name interface{}) *MockDeviceService_UpdateDeviceName_Call {
	return &MockDeviceService_UpdateDeviceName_Call{Call: _e.mock.On("UpdateDeviceName", ctx, userID, id, name)}
}

func (_c *MockDeviceService_UpdateDeviceName_Call) Run(run func(ctx context.Context, userID uint, id uint, name string)) *MockDeviceService_UpdateDeviceName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDeviceService_UpdateDeviceName_Call) Return(device *db.Device, err error) *MockDeviceService_UpdateDeviceName_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockDeviceService_UpdateDeviceName_Call) RunAndReturn(run func(ctx context.Context, userID uint, id uint, name string) (*db.Device, error)) *MockDeviceService_UpdateDeviceName_Call {
	_c.Call.Return(run)
	return _c
}
