// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-lbry/internal/db"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"go.lumeweb.com/queryutil"
	"gorm.io/gorm"
)

// NewMockDeviceService creates a new instance of MockDeviceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceService {
	mock := &MockDeviceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeviceService is an autogenerated mock type for the DeviceService type
type MockDeviceService struct {
	mock.Mock
}

type MockDeviceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceService) EXPECT() *MockDeviceService_Expecter {
	return &MockDeviceService_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockDeviceService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockDeviceService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockDeviceService_Expecter) Config() *MockDeviceService_Config_Call {
	return &MockDeviceService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockDeviceService_Config_Call) Run(run func()) *MockDeviceService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceService_Config_Call) Return(manager config.Manager) *MockDeviceService_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockDeviceService_Config_Call) RunAndReturn(run func() config.Manager) *MockDeviceService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockDeviceService_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockDeviceService_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockDeviceService_Expecter) Context() *MockDeviceService_Context_Call {
	return &MockDeviceService_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockDeviceService_Context_Call) Run(run func()) *MockDeviceService_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceService_Context_Call) Return(context core.Context) *MockDeviceService_Context_Call {
	_c.Call.Return(context)
	return _c
}

func (_c *MockDeviceService_Context_Call) RunAndReturn(run func() core.Context) *MockDeviceService_Context_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDevice provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) CreateDevice(ctx context.Context, userID uint, name string, ipAddress string) (*db.Device, error) {
	ret := _mock.Called(ctx, userID, name, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for CreateDevice")
	}

	var r0 *db.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, string) (*db.Device, error)); ok {
		return returnFunc(ctx, userID, name, ipAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, string) *db.Device); ok {
		r0 = returnFunc(ctx, userID, name, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string, string) error); ok {
		r1 = returnFunc(ctx, userID, name, ipAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceService_CreateDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDevice'
type MockDeviceService_CreateDevice_Call struct {
	*mock.Call
}

// CreateDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - name string
//   - ipAddress string
func (_e *MockDeviceService_Expecter) CreateDevice(ctx interface{}, userID interface{}, name interface{}, ipAddress interface{}) *MockDeviceService_CreateDevice_Call {
	return &MockDeviceService_CreateDevice_Call{Call: _e.mock.On("CreateDevice", ctx, userID, name, ipAddress)}
}

func (_c *MockDeviceService_CreateDevice_Call) Run(run func(ctx context.Context, userID uint, name string, ipAddress string)) *MockDeviceService_CreateDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDeviceService_CreateDevice_Call) Return(device *db.Device, err error) *MockDeviceService_CreateDevice_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockDeviceService_CreateDevice_Call) RunAndReturn(run func(ctx context.Context, userID uint, name string, ipAddress string) (*db.Device, error)) *MockDeviceService_CreateDevice_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockDeviceService_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockDeviceService_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockDeviceService_Expecter) DB() *MockDeviceService_DB_Call {
	return &MockDeviceService_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockDeviceService_DB_Call) Run(run func()) *MockDeviceService_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceService_DB_Call) Return(dB *gorm.DB) *MockDeviceService_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockDeviceService_DB_Call) RunAndReturn(run func() *gorm.DB) *MockDeviceService_DB_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDevice provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) DeleteDevice(ctx context.Context, userID uint, id uint) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDevice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceService_DeleteDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDevice'
type MockDeviceService_DeleteDevice_Call struct {
	*mock.Call
}

// DeleteDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - id uint
func (_e *MockDeviceService_Expecter) DeleteDevice(ctx interface{}, userID interface{}, id interface{}) *MockDeviceService_DeleteDevice_Call {
	return &MockDeviceService_DeleteDevice_Call{Call: _e.mock.On("DeleteDevice", ctx, userID, id)}
}

func (_c *MockDeviceService_DeleteDevice_Call) Run(run func(ctx context.Context, userID uint, id uint)) *MockDeviceService_DeleteDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeviceService_DeleteDevice_Call) Return(err error) *MockDeviceService_DeleteDevice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceService_DeleteDevice_Call) RunAndReturn(run func(ctx context.Context, userID uint, id uint) error) *MockDeviceService_DeleteDevice_Call {
	_c.Call.Return(run)
	return _c
}

// GetDevice provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) GetDevice(ctx context.Context, userID uint, id uint) (*db.Device, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDevice")
	}

	var r0 *db.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) (*db.Device, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) *db.Device); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceService_GetDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDevice'
type MockDeviceService_GetDevice_Call struct {
	*mock.Call
}

// GetDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - id uint
func (_e *MockDeviceService_Expecter) GetDevice(ctx interface{}, userID interface{}, id interface{}) *MockDeviceService_GetDevice_Call {
	return &MockDeviceService_GetDevice_Call{Call: _e.mock.On("GetDevice", ctx, userID, id)}
}

func (_c *MockDeviceService_GetDevice_Call) Run(run func(ctx context.Context, userID uint, id uint)) *MockDeviceService_GetDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeviceService_GetDevice_Call) Return(device *db.Device, err error) *MockDeviceService_GetDevice_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockDeviceService_GetDevice_Call) RunAndReturn(run func(ctx context.Context, userID uint, id uint) (*db.Device, error)) *MockDeviceService_GetDevice_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeviceByIPAddress provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) GetDeviceByIPAddress(ctx context.Context, ipAddress string) (*db.Device, error) {
	ret := _mock.Called(ctx, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetDeviceByIPAddress")
	}

	var r0 *db.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*db.Device, error)); ok {
		return returnFunc(ctx, ipAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *db.Device); ok {
		r0 = returnFunc(ctx, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ipAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceService_GetDeviceByIPAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeviceByIPAddress'
type MockDeviceService_GetDeviceByIPAddress_Call struct {
	*mock.Call
}

// GetDeviceByIPAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - ipAddress string
func (_e *MockDeviceService_Expecter) GetDeviceByIPAddress(ctx interface{}, ipAddress interface{}) *MockDeviceService_GetDeviceByIPAddress_Call {
	return &MockDeviceService_GetDeviceByIPAddress_Call{Call: _e.mock.On("GetDeviceByIPAddress", ctx, ipAddress)}
}

func (_c *MockDeviceService_GetDeviceByIPAddress_Call) Run(run func(ctx context.Context, ipAddress string)) *MockDeviceService_GetDeviceByIPAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceService_GetDeviceByIPAddress_Call) Return(device *db.Device, err error) *MockDeviceService_GetDeviceByIPAddress_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockDeviceService_GetDeviceByIPAddress_Call) RunAndReturn(run func(ctx context.Context, ipAddress string) (*db.Device, error)) *MockDeviceService_GetDeviceByIPAddress_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDeviceService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockDeviceService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockDeviceService_Expecter) ID() *MockDeviceService_ID_Call {
	return &MockDeviceService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockDeviceService_ID_Call) Run(run func()) *MockDeviceService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceService_ID_Call) Return(s string) *MockDeviceService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDeviceService_ID_Call) RunAndReturn(run func() string) *MockDeviceService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ListDevices provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) ListDevices(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*db.Device, int64, error) {
	ret := _mock.Called(ctx, userID, filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListDevices")
	}

	var r0 []*db.Device
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) ([]*db.Device, int64, error)); ok {
		return returnFunc(ctx, userID, filters, sorts, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) []*db.Device); ok {
		r0 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*db.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockDeviceService_ListDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDevices'
type MockDeviceService_ListDevices_Call struct {
	*mock.Call
}

// ListDevices is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - filters []queryutil.CrudFilter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockDeviceService_Expecter) ListDevices(ctx interface{}, userID interface{}, filters interface{}, sorts interface{}, pagination interface{}) *MockDeviceService_ListDevices_Call {
	return &MockDeviceService_ListDevices_Call{Call: _e.mock.On("ListDevices", ctx, userID, filters, sorts, pagination)}
}

func (_c *MockDeviceService_ListDevices_Call) Run(run func(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockDeviceService_ListDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 []queryutil.CrudFilter
		if args[2] != nil {
			arg2 = args[2].([]queryutil.CrudFilter)
		}
		var arg3 []queryutil.Sort
		if args[3] != nil {
			arg3 = args[3].([]queryutil.Sort)
		}
		var arg4 queryutil.Pagination
		if args[4] != nil {
			arg4 = args[4].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockDeviceService_ListDevices_Call) Return(devices []*db.Device, n int64, err error) *MockDeviceService_ListDevices_Call {
	_c.Call.Return(devices, n, err)
	return _c
}

func (_c *MockDeviceService_ListDevices_Call) RunAndReturn(run func(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*db.Device, int64, error)) *MockDeviceService_ListDevices_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockDeviceService_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockDeviceService_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockDeviceService_Expecter) Logger() *MockDeviceService_Logger_Call {
	return &MockDeviceService_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockDeviceService_Logger_Call) Run(run func()) *MockDeviceService_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceService_Logger_Call) Return(logger *core.Logger) *MockDeviceService_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockDeviceService_Logger_Call) RunAndReturn(run func() *core.Logger) *MockDeviceService_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockDeviceService_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockDeviceService_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockDeviceService_Expecter) SetConfig(cfg interface{}) *MockDeviceService_SetConfig_Call {
	return &MockDeviceService_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockDeviceService_SetConfig_Call) Run(run func(cfg config.Manager)) *MockDeviceService_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeviceService_SetConfig_Call) Return() *MockDeviceService_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDeviceService_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockDeviceService_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockDeviceService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockDeviceService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockDeviceService_Expecter) SetContext(ctx interface{}) *MockDeviceService_SetContext_Call {
	return &MockDeviceService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockDeviceService_SetContext_Call) Run(run func(ctx core.Context)) *MockDeviceService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeviceService_SetContext_Call) Return() *MockDeviceService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDeviceService_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockDeviceService_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) SetDB(db1 *gorm.DB) {
	_mock.Called(db1)
	return
}

// MockDeviceService_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockDeviceService_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db1 *gorm.DB
func (_e *MockDeviceService_Expecter) SetDB(db1 interface{}) *MockDeviceService_SetDB_Call {
	return &MockDeviceService_SetDB_Call{Call: _e.mock.On("SetDB", db1)}
}

func (_c *MockDeviceService_SetDB_Call) Run(run func(db1 *gorm.DB)) *MockDeviceService_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeviceService_SetDB_Call) Return() *MockDeviceService_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDeviceService_SetDB_Call) RunAndReturn(run func(db1 *gorm.DB)) *MockDeviceService_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockDeviceService_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockDeviceService_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockDeviceService_Expecter) SetLogger(logger interface{}) *MockDeviceService_SetLogger_Call {
	return &MockDeviceService_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockDeviceService_SetLogger_Call) Run(run func(logger *core.Logger)) *MockDeviceService_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeviceService_SetLogger_Call) Return() *MockDeviceService_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDeviceService_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockDeviceService_SetLogger_Call {
	_c.Run(run)
	return _c
}

// UpdateDevice provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) UpdateDevice(ctx context.Context, userID uint, id uint, name string, ipAddress string) (*db.Device, error) {
	ret := _mock.Called(ctx, userID, id, name, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDevice")
	}

	var r0 *db.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, string, string) (*db.Device, error)); ok {
		return returnFunc(ctx, userID, id, name, ipAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, string, string) *db.Device); ok {
		r0 = returnFunc(ctx, userID, id, name, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint, string, string) error); ok {
		r1 = returnFunc(ctx, userID, id, name, ipAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceService_UpdateDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDevice'
type MockDeviceService_UpdateDevice_Call struct {
	*mock.Call
}

// UpdateDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - id uint
//   - name string
//   - ipAddress string
func (_e *MockDeviceService_Expecter) UpdateDevice(ctx interface{}, userID interface{}, id interface{}, name interface{}, ipAddress interface{}) *MockDeviceService_UpdateDevice_Call {
	return &MockDeviceService_UpdateDevice_Call{Call: _e.mock.On("UpdateDevice", ctx, userID, id, name, ipAddress)}
}

func (_c *MockDeviceService_UpdateDevice_Call) Run(run func(ctx context.Context, userID uint, id uint, name string, ipAddress string)) *MockDeviceService_UpdateDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockDeviceService_UpdateDevice_Call) Return(device *db.Device, err error) *MockDeviceService_UpdateDevice_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockDeviceService_UpdateDevice_Call) RunAndReturn(run func(ctx context.Context, userID uint, id uint, name string, ipAddress string) (*db.Device, error)) *MockDeviceService_UpdateDevice_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDeviceName provides a mock function for the type MockDeviceService
func (_mock *MockDeviceService) UpdateDeviceName(ctx context.Context, userID uint, id uint, name string) (*db.Device, error) {
	ret := _mock.Called(ctx, userID, id, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDeviceName")
	}

	var r0 *db.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, string) (*db.Device, error)); ok {
		return returnFunc(ctx, userID, id, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, string) *db.Device); ok {
		r0 = returnFunc(ctx, userID, id, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint, string) error); ok {
		r1 = returnFunc(ctx, userID, id, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceService_UpdateDeviceName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDeviceName'
type MockDeviceService_UpdateDeviceName_Call struct {
	*mock.Call
}

// UpdateDeviceName is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - id uint
//   - name string
func (_e *MockDeviceService_Expecter) UpdateDeviceName(ctx interface{}, userID interface{}, id interface{}, name interface{}) *MockDeviceService_UpdateDeviceName_Call {
	return &MockDeviceService_UpdateDeviceName_Call{Call: _e.mock.On("UpdateDeviceName", ctx, userID, id, name)}
}

func (_c *MockDeviceService_UpdateDeviceName_Call) Run(run func(ctx context.Context, userID uint, id uint, name string)) *MockDeviceService_UpdateDeviceName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDeviceService_UpdateDeviceName_Call) Return(device *db.Device, err error) *MockDeviceService_UpdateDeviceName_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockDeviceService_UpdateDeviceName_Call) RunAndReturn(run func(ctx context.Context, userID uint, id uint, name string) (*db.Device, error)) *MockDeviceService_UpdateDeviceName_Call {
	_c.Call.Return(run)
	return _c
}
