// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/ipfs/go-cid"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/liblbry/stream"
	"go.lumeweb.com/portal-plugin-lbry/internal/db"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"go.lumeweb.com/queryutil"
	"gorm.io/gorm"
)

// NewMockUploadService creates a new instance of MockUploadService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUploadService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUploadService {
	mock := &MockUploadService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUploadService is an autogenerated mock type for the UploadService type
type MockUploadService struct {
	mock.Mock
}

type MockUploadService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUploadService) EXPECT() *MockUploadService_Expecter {
	return &MockUploadService_Expecter{mock: &_m.Mock}
}

// CleanupPendingBlobs provides a mock function for the type MockUploadService
func (_mock *MockUploadService) CleanupPendingBlobs(ctx context.Context, userID uint, streamResult *stream.StreamResult) error {
	ret := _mock.Called(ctx, userID, streamResult)

	if len(ret) == 0 {
		panic("no return value specified for CleanupPendingBlobs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, *stream.StreamResult) error); ok {
		r0 = returnFunc(ctx, userID, streamResult)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUploadService_CleanupPendingBlobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupPendingBlobs'
type MockUploadService_CleanupPendingBlobs_Call struct {
	*mock.Call
}

// CleanupPendingBlobs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - streamResult *stream.StreamResult
func (_e *MockUploadService_Expecter) CleanupPendingBlobs(ctx interface{}, userID interface{}, streamResult interface{}) *MockUploadService_CleanupPendingBlobs_Call {
	return &MockUploadService_CleanupPendingBlobs_Call{Call: _e.mock.On("CleanupPendingBlobs", ctx, userID, streamResult)}
}

func (_c *MockUploadService_CleanupPendingBlobs_Call) Run(run func(ctx context.Context, userID uint, streamResult *stream.StreamResult)) *MockUploadService_CleanupPendingBlobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 *stream.StreamResult
		if args[2] != nil {
			arg2 = args[2].(*stream.StreamResult)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUploadService_CleanupPendingBlobs_Call) Return(err error) *MockUploadService_CleanupPendingBlobs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUploadService_CleanupPendingBlobs_Call) RunAndReturn(run func(ctx context.Context, userID uint, streamResult *stream.StreamResult) error) *MockUploadService_CleanupPendingBlobs_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type MockUploadService
func (_mock *MockUploadService) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockUploadService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockUploadService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockUploadService_Expecter) Config() *MockUploadService_Config_Call {
	return &MockUploadService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockUploadService_Config_Call) Run(run func()) *MockUploadService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUploadService_Config_Call) Return(manager config.Manager) *MockUploadService_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockUploadService_Config_Call) RunAndReturn(run func() config.Manager) *MockUploadService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockUploadService
func (_mock *MockUploadService) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockUploadService_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockUploadService_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockUploadService_Expecter) Context() *MockUploadService_Context_Call {
	return &MockUploadService_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockUploadService_Context_Call) Run(run func()) *MockUploadService_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUploadService_Context_Call) Return(context1 core.Context) *MockUploadService_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockUploadService_Context_Call) RunAndReturn(run func() core.Context) *MockUploadService_Context_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStreamPin provides a mock function for the type MockUploadService
func (_mock *MockUploadService) CreateStreamPin(ctx context.Context, userId uint, sdCid cid.Cid) (*db.StreamPin, error) {
	ret := _mock.Called(ctx, userId, sdCid)

	if len(ret) == 0 {
		panic("no return value specified for CreateStreamPin")
	}

	var r0 *db.StreamPin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, cid.Cid) (*db.StreamPin, error)); ok {
		return returnFunc(ctx, userId, sdCid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, cid.Cid) *db.StreamPin); ok {
		r0 = returnFunc(ctx, userId, sdCid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.StreamPin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, cid.Cid) error); ok {
		r1 = returnFunc(ctx, userId, sdCid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_CreateStreamPin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStreamPin'
type MockUploadService_CreateStreamPin_Call struct {
	*mock.Call
}

// CreateStreamPin is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uint
//   - sdCid cid.Cid
func (_e *MockUploadService_Expecter) CreateStreamPin(ctx interface{}, userId interface{}, sdCid interface{}) *MockUploadService_CreateStreamPin_Call {
	return &MockUploadService_CreateStreamPin_Call{Call: _e.mock.On("CreateStreamPin", ctx, userId, sdCid)}
}

func (_c *MockUploadService_CreateStreamPin_Call) Run(run func(ctx context.Context, userId uint, sdCid cid.Cid)) *MockUploadService_CreateStreamPin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 cid.Cid
		if args[2] != nil {
			arg2 = args[2].(cid.Cid)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUploadService_CreateStreamPin_Call) Return(streamPin *db.StreamPin, err error) *MockUploadService_CreateStreamPin_Call {
	_c.Call.Return(streamPin, err)
	return _c
}

func (_c *MockUploadService_CreateStreamPin_Call) RunAndReturn(run func(ctx context.Context, userId uint, sdCid cid.Cid) (*db.StreamPin, error)) *MockUploadService_CreateStreamPin_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockUploadService
func (_mock *MockUploadService) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockUploadService_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockUploadService_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockUploadService_Expecter) DB() *MockUploadService_DB_Call {
	return &MockUploadService_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockUploadService_DB_Call) Run(run func()) *MockUploadService_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUploadService_DB_Call) Return(dB *gorm.DB) *MockUploadService_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockUploadService_DB_Call) RunAndReturn(run func() *gorm.DB) *MockUploadService_DB_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStream provides a mock function for the type MockUploadService
func (_mock *MockUploadService) DeleteStream(ctx context.Context, userID uint, sdHash string) error {
	ret := _mock.Called(ctx, userID, sdHash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStream")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = returnFunc(ctx, userID, sdHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUploadService_DeleteStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStream'
type MockUploadService_DeleteStream_Call struct {
	*mock.Call
}

// DeleteStream is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - sdHash string
func (_e *MockUploadService_Expecter) DeleteStream(ctx interface{}, userID interface{}, sdHash interface{}) *MockUploadService_DeleteStream_Call {
	return &MockUploadService_DeleteStream_Call{Call: _e.mock.On("DeleteStream", ctx, userID, sdHash)}
}

func (_c *MockUploadService_DeleteStream_Call) Run(run func(ctx context.Context, userID uint, sdHash string)) *MockUploadService_DeleteStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUploadService_DeleteStream_Call) Return(err error) *MockUploadService_DeleteStream_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUploadService_DeleteStream_Call) RunAndReturn(run func(ctx context.Context, userID uint, sdHash string) error) *MockUploadService_DeleteStream_Call {
	_c.Call.Return(run)
	return _c
}

// GetMissingBlobs provides a mock function for the type MockUploadService
func (_mock *MockUploadService) GetMissingBlobs(ctx context.Context, userID uint, streamID uint, requiredBlobs []string) ([]string, error) {
	ret := _mock.Called(ctx, userID, streamID, requiredBlobs)

	if len(ret) == 0 {
		panic("no return value specified for GetMissingBlobs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, []string) ([]string, error)); ok {
		return returnFunc(ctx, userID, streamID, requiredBlobs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, []string) []string); ok {
		r0 = returnFunc(ctx, userID, streamID, requiredBlobs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint, []string) error); ok {
		r1 = returnFunc(ctx, userID, streamID, requiredBlobs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_GetMissingBlobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMissingBlobs'
type MockUploadService_GetMissingBlobs_Call struct {
	*mock.Call
}

// GetMissingBlobs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - streamID uint
//   - requiredBlobs []string
func (_e *MockUploadService_Expecter) GetMissingBlobs(ctx interface{}, userID interface{}, streamID interface{}, requiredBlobs interface{}) *MockUploadService_GetMissingBlobs_Call {
	return &MockUploadService_GetMissingBlobs_Call{Call: _e.mock.On("GetMissingBlobs", ctx, userID, streamID, requiredBlobs)}
}

func (_c *MockUploadService_GetMissingBlobs_Call) Run(run func(ctx context.Context, userID uint, streamID uint, requiredBlobs []string)) *MockUploadService_GetMissingBlobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUploadService_GetMissingBlobs_Call) Return(strings []string, err error) *MockUploadService_GetMissingBlobs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockUploadService_GetMissingBlobs_Call) RunAndReturn(run func(ctx context.Context, userID uint, streamID uint, requiredBlobs []string) ([]string, error)) *MockUploadService_GetMissingBlobs_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingBlobCount provides a mock function for the type MockUploadService
func (_mock *MockUploadService) GetPendingBlobCount(ctx context.Context, userID uint, streamID uint) (int64, error) {
	ret := _mock.Called(ctx, userID, streamID)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingBlobCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) (int64, error)); ok {
		return returnFunc(ctx, userID, streamID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) int64); ok {
		r0 = returnFunc(ctx, userID, streamID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = returnFunc(ctx, userID, streamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_GetPendingBlobCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingBlobCount'
type MockUploadService_GetPendingBlobCount_Call struct {
	*mock.Call
}

// GetPendingBlobCount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - streamID uint
func (_e *MockUploadService_Expecter) GetPendingBlobCount(ctx interface{}, userID interface{}, streamID interface{}) *MockUploadService_GetPendingBlobCount_Call {
	return &MockUploadService_GetPendingBlobCount_Call{Call: _e.mock.On("GetPendingBlobCount", ctx, userID, streamID)}
}

func (_c *MockUploadService_GetPendingBlobCount_Call) Run(run func(ctx context.Context, userID uint, streamID uint)) *MockUploadService_GetPendingBlobCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUploadService_GetPendingBlobCount_Call) Return(n int64, err error) *MockUploadService_GetPendingBlobCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUploadService_GetPendingBlobCount_Call) RunAndReturn(run func(ctx context.Context, userID uint, streamID uint) (int64, error)) *MockUploadService_GetPendingBlobCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingBlobs provides a mock function for the type MockUploadService
func (_mock *MockUploadService) GetPendingBlobs(ctx context.Context, userID uint, sdHash string) ([]*db.PendingBlob, error) {
	ret := _mock.Called(ctx, userID, sdHash)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingBlobs")
	}

	var r0 []*db.PendingBlob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) ([]*db.PendingBlob, error)); ok {
		return returnFunc(ctx, userID, sdHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) []*db.PendingBlob); ok {
		r0 = returnFunc(ctx, userID, sdHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*db.PendingBlob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = returnFunc(ctx, userID, sdHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_GetPendingBlobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingBlobs'
type MockUploadService_GetPendingBlobs_Call struct {
	*mock.Call
}

// GetPendingBlobs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - sdHash string
func (_e *MockUploadService_Expecter) GetPendingBlobs(ctx interface{}, userID interface{}, sdHash interface{}) *MockUploadService_GetPendingBlobs_Call {
	return &MockUploadService_GetPendingBlobs_Call{Call: _e.mock.On("GetPendingBlobs", ctx, userID, sdHash)}
}

func (_c *MockUploadService_GetPendingBlobs_Call) Run(run func(ctx context.Context, userID uint, sdHash string)) *MockUploadService_GetPendingBlobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUploadService_GetPendingBlobs_Call) Return(pendingBlobs []*db.PendingBlob, err error) *MockUploadService_GetPendingBlobs_Call {
	_c.Call.Return(pendingBlobs, err)
	return _c
}

func (_c *MockUploadService_GetPendingBlobs_Call) RunAndReturn(run func(ctx context.Context, userID uint, sdHash string) ([]*db.PendingBlob, error)) *MockUploadService_GetPendingBlobs_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingStream provides a mock function for the type MockUploadService
func (_mock *MockUploadService) GetPendingStream(ctx context.Context, userID uint, sdHash string) (*db.PendingStream, error) {
	ret := _mock.Called(ctx, userID, sdHash)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingStream")
	}

	var r0 *db.PendingStream
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) (*db.PendingStream, error)); ok {
		return returnFunc(ctx, userID, sdHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) *db.PendingStream); ok {
		r0 = returnFunc(ctx, userID, sdHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.PendingStream)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = returnFunc(ctx, userID, sdHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_GetPendingStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingStream'
type MockUploadService_GetPendingStream_Call struct {
	*mock.Call
}

// GetPendingStream is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - sdHash string
func (_e *MockUploadService_Expecter) GetPendingStream(ctx interface{}, userID interface{}, sdHash interface{}) *MockUploadService_GetPendingStream_Call {
	return &MockUploadService_GetPendingStream_Call{Call: _e.mock.On("GetPendingStream", ctx, userID, sdHash)}
}

func (_c *MockUploadService_GetPendingStream_Call) Run(run func(ctx context.Context, userID uint, sdHash string)) *MockUploadService_GetPendingStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUploadService_GetPendingStream_Call) Return(pendingStream *db.PendingStream, err error) *MockUploadService_GetPendingStream_Call {
	_c.Call.Return(pendingStream, err)
	return _c
}

func (_c *MockUploadService_GetPendingStream_Call) RunAndReturn(run func(ctx context.Context, userID uint, sdHash string) (*db.PendingStream, error)) *MockUploadService_GetPendingStream_Call {
	_c.Call.Return(run)
	return _c
}

// GetStreamSize provides a mock function for the type MockUploadService
func (_mock *MockUploadService) GetStreamSize(ctx context.Context, streamID uint64) (int64, error) {
	ret := _mock.Called(ctx, streamID)

	if len(ret) == 0 {
		panic("no return value specified for GetStreamSize")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (int64, error)); ok {
		return returnFunc(ctx, streamID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) int64); ok {
		r0 = returnFunc(ctx, streamID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, streamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_GetStreamSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStreamSize'
type MockUploadService_GetStreamSize_Call struct {
	*mock.Call
}

// GetStreamSize is a helper method to define mock.On call
//   - ctx context.Context
//   - streamID uint64
func (_e *MockUploadService_Expecter) GetStreamSize(ctx interface{}, streamID interface{}) *MockUploadService_GetStreamSize_Call {
	return &MockUploadService_GetStreamSize_Call{Call: _e.mock.On("GetStreamSize", ctx, streamID)}
}

func (_c *MockUploadService_GetStreamSize_Call) Run(run func(ctx context.Context, streamID uint64)) *MockUploadService_GetStreamSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadService_GetStreamSize_Call) Return(n int64, err error) *MockUploadService_GetStreamSize_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUploadService_GetStreamSize_Call) RunAndReturn(run func(ctx context.Context, streamID uint64) (int64, error)) *MockUploadService_GetStreamSize_Call {
	_c.Call.Return(run)
	return _c
}

// HandleUpload provides a mock function for the type MockUploadService
func (_mock *MockUploadService) HandleUpload(ctx context.Context, reader io.ReadSeekCloser) (cid.Cid, string, error) {
	ret := _mock.Called(ctx, reader)

	if len(ret) == 0 {
		panic("no return value specified for HandleUpload")
	}

	var r0 cid.Cid
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.ReadSeekCloser) (cid.Cid, string, error)); ok {
		return returnFunc(ctx, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.ReadSeekCloser) cid.Cid); ok {
		r0 = returnFunc(ctx, reader)
	} else {
		r0 = ret.Get(0).(cid.Cid)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.ReadSeekCloser) string); ok {
		r1 = returnFunc(ctx, reader)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, io.ReadSeekCloser) error); ok {
		r2 = returnFunc(ctx, reader)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUploadService_HandleUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleUpload'
type MockUploadService_HandleUpload_Call struct {
	*mock.Call
}

// HandleUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - reader io.ReadSeekCloser
func (_e *MockUploadService_Expecter) HandleUpload(ctx interface{}, reader interface{}) *MockUploadService_HandleUpload_Call {
	return &MockUploadService_HandleUpload_Call{Call: _e.mock.On("HandleUpload", ctx, reader)}
}

func (_c *MockUploadService_HandleUpload_Call) Run(run func(ctx context.Context, reader io.ReadSeekCloser)) *MockUploadService_HandleUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.ReadSeekCloser
		if args[1] != nil {
			arg1 = args[1].(io.ReadSeekCloser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadService_HandleUpload_Call) Return(cid1 cid.Cid, s string, err error) *MockUploadService_HandleUpload_Call {
	_c.Call.Return(cid1, s, err)
	return _c
}

func (_c *MockUploadService_HandleUpload_Call) RunAndReturn(run func(ctx context.Context, reader io.ReadSeekCloser) (cid.Cid, string, error)) *MockUploadService_HandleUpload_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockUploadService
func (_mock *MockUploadService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUploadService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockUploadService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockUploadService_Expecter) ID() *MockUploadService_ID_Call {
	return &MockUploadService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockUploadService_ID_Call) Run(run func()) *MockUploadService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUploadService_ID_Call) Return(s string) *MockUploadService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUploadService_ID_Call) RunAndReturn(run func() string) *MockUploadService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ListStreams provides a mock function for the type MockUploadService
func (_mock *MockUploadService) ListStreams(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*db.Stream, int64, error) {
	ret := _mock.Called(ctx, userID, filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListStreams")
	}

	var r0 []*db.Stream
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) ([]*db.Stream, int64, error)); ok {
		return returnFunc(ctx, userID, filters, sorts, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) []*db.Stream); ok {
		r0 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*db.Stream)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUploadService_ListStreams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStreams'
type MockUploadService_ListStreams_Call struct {
	*mock.Call
}

// ListStreams is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - filters []queryutil.CrudFilter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockUploadService_Expecter) ListStreams(ctx interface{}, userID interface{}, filters interface{}, sorts interface{}, pagination interface{}) *MockUploadService_ListStreams_Call {
	return &MockUploadService_ListStreams_Call{Call: _e.mock.On("ListStreams", ctx, userID, filters, sorts, pagination)}
}

func (_c *MockUploadService_ListStreams_Call) Run(run func(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockUploadService_ListStreams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 []queryutil.CrudFilter
		if args[2] != nil {
			arg2 = args[2].([]queryutil.CrudFilter)
		}
		var arg3 []queryutil.Sort
		if args[3] != nil {
			arg3 = args[3].([]queryutil.Sort)
		}
		var arg4 queryutil.Pagination
		if args[4] != nil {
			arg4 = args[4].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUploadService_ListStreams_Call) Return(streams []*db.Stream, n int64, err error) *MockUploadService_ListStreams_Call {
	_c.Call.Return(streams, n, err)
	return _c
}

func (_c *MockUploadService_ListStreams_Call) RunAndReturn(run func(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*db.Stream, int64, error)) *MockUploadService_ListStreams_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockUploadService
func (_mock *MockUploadService) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockUploadService_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockUploadService_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockUploadService_Expecter) Logger() *MockUploadService_Logger_Call {
	return &MockUploadService_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockUploadService_Logger_Call) Run(run func()) *MockUploadService_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUploadService_Logger_Call) Return(logger *core.Logger) *MockUploadService_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockUploadService_Logger_Call) RunAndReturn(run func() *core.Logger) *MockUploadService_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPendingBlobAsReceived provides a mock function for the type MockUploadService
func (_mock *MockUploadService) MarkPendingBlobAsReceived(ctx context.Context, userID uint, deviceID uint, blobInfo *stream.BlobInfo) error {
	ret := _mock.Called(ctx, userID, deviceID, blobInfo)

	if len(ret) == 0 {
		panic("no return value specified for MarkPendingBlobAsReceived")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, *stream.BlobInfo) error); ok {
		r0 = returnFunc(ctx, userID, deviceID, blobInfo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUploadService_MarkPendingBlobAsReceived_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPendingBlobAsReceived'
type MockUploadService_MarkPendingBlobAsReceived_Call struct {
	*mock.Call
}

// MarkPendingBlobAsReceived is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - deviceID uint
//   - blobInfo *stream.BlobInfo
func (_e *MockUploadService_Expecter) MarkPendingBlobAsReceived(ctx interface{}, userID interface{}, deviceID interface{}, blobInfo interface{}) *MockUploadService_MarkPendingBlobAsReceived_Call {
	return &MockUploadService_MarkPendingBlobAsReceived_Call{Call: _e.mock.On("MarkPendingBlobAsReceived", ctx, userID, deviceID, blobInfo)}
}

func (_c *MockUploadService_MarkPendingBlobAsReceived_Call) Run(run func(ctx context.Context, userID uint, deviceID uint, blobInfo *stream.BlobInfo)) *MockUploadService_MarkPendingBlobAsReceived_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 *stream.BlobInfo
		if args[3] != nil {
			arg3 = args[3].(*stream.BlobInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUploadService_MarkPendingBlobAsReceived_Call) Return(err error) *MockUploadService_MarkPendingBlobAsReceived_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUploadService_MarkPendingBlobAsReceived_Call) RunAndReturn(run func(ctx context.Context, userID uint, deviceID uint, blobInfo *stream.BlobInfo) error) *MockUploadService_MarkPendingBlobAsReceived_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessUpload provides a mock function for the type MockUploadService
func (_mock *MockUploadService) ProcessUpload(ctx context.Context, result *stream.StreamResult, userId uint) error {
	ret := _mock.Called(ctx, result, userId)

	if len(ret) == 0 {
		panic("no return value specified for ProcessUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *stream.StreamResult, uint) error); ok {
		r0 = returnFunc(ctx, result, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUploadService_ProcessUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessUpload'
type MockUploadService_ProcessUpload_Call struct {
	*mock.Call
}

// ProcessUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - result *stream.StreamResult
//   - userId uint
func (_e *MockUploadService_Expecter) ProcessUpload(ctx interface{}, result interface{}, userId interface{}) *MockUploadService_ProcessUpload_Call {
	return &MockUploadService_ProcessUpload_Call{Call: _e.mock.On("ProcessUpload", ctx, result, userId)}
}

func (_c *MockUploadService_ProcessUpload_Call) Run(run func(ctx context.Context, result *stream.StreamResult, userId uint)) *MockUploadService_ProcessUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *stream.StreamResult
		if args[1] != nil {
			arg1 = args[1].(*stream.StreamResult)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUploadService_ProcessUpload_Call) Return(err error) *MockUploadService_ProcessUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUploadService_ProcessUpload_Call) RunAndReturn(run func(ctx context.Context, result *stream.StreamResult, userId uint) error) *MockUploadService_ProcessUpload_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockUploadService
func (_mock *MockUploadService) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockUploadService_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockUploadService_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockUploadService_Expecter) SetConfig(cfg interface{}) *MockUploadService_SetConfig_Call {
	return &MockUploadService_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockUploadService_SetConfig_Call) Run(run func(cfg config.Manager)) *MockUploadService_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUploadService_SetConfig_Call) Return() *MockUploadService_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUploadService_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockUploadService_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockUploadService
func (_mock *MockUploadService) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockUploadService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockUploadService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockUploadService_Expecter) SetContext(ctx interface{}) *MockUploadService_SetContext_Call {
	return &MockUploadService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockUploadService_SetContext_Call) Run(run func(ctx core.Context)) *MockUploadService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUploadService_SetContext_Call) Return() *MockUploadService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUploadService_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockUploadService_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockUploadService
func (_mock *MockUploadService) SetDB(db1 *gorm.DB) {
	_mock.Called(db1)
	return
}

// MockUploadService_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockUploadService_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db1 *gorm.DB
func (_e *MockUploadService_Expecter) SetDB(db1 interface{}) *MockUploadService_SetDB_Call {
	return &MockUploadService_SetDB_Call{Call: _e.mock.On("SetDB", db1)}
}

func (_c *MockUploadService_SetDB_Call) Run(run func(db1 *gorm.DB)) *MockUploadService_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUploadService_SetDB_Call) Return() *MockUploadService_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUploadService_SetDB_Call) RunAndReturn(run func(db1 *gorm.DB)) *MockUploadService_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockUploadService
func (_mock *MockUploadService) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockUploadService_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockUploadService_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockUploadService_Expecter) SetLogger(logger interface{}) *MockUploadService_SetLogger_Call {
	return &MockUploadService_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockUploadService_SetLogger_Call) Run(run func(logger *core.Logger)) *MockUploadService_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUploadService_SetLogger_Call) Return() *MockUploadService_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUploadService_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockUploadService_SetLogger_Call {
	_c.Run(run)
	return _c
}

// StorePendingBlob provides a mock function for the type MockUploadService
func (_mock *MockUploadService) StorePendingBlob(ctx context.Context, userID uint, deviceID uint, streamID uint, blobInfo *stream.BlobInfo) error {
	ret := _mock.Called(ctx, userID, deviceID, streamID, blobInfo)

	if len(ret) == 0 {
		panic("no return value specified for StorePendingBlob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, uint, *stream.BlobInfo) error); ok {
		r0 = returnFunc(ctx, userID, deviceID, streamID, blobInfo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUploadService_StorePendingBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorePendingBlob'
type MockUploadService_StorePendingBlob_Call struct {
	*mock.Call
}

// StorePendingBlob is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - deviceID uint
//   - streamID uint
//   - blobInfo *stream.BlobInfo
func (_e *MockUploadService_Expecter) StorePendingBlob(ctx interface{}, userID interface{}, deviceID interface{}, streamID interface{}, blobInfo interface{}) *MockUploadService_StorePendingBlob_Call {
	return &MockUploadService_StorePendingBlob_Call{Call: _e.mock.On("StorePendingBlob", ctx, userID, deviceID, streamID, blobInfo)}
}

func (_c *MockUploadService_StorePendingBlob_Call) Run(run func(ctx context.Context, userID uint, deviceID uint, streamID uint, blobInfo *stream.BlobInfo)) *MockUploadService_StorePendingBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 uint
		if args[3] != nil {
			arg3 = args[3].(uint)
		}
		var arg4 *stream.BlobInfo
		if args[4] != nil {
			arg4 = args[4].(*stream.BlobInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUploadService_StorePendingBlob_Call) Return(err error) *MockUploadService_StorePendingBlob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUploadService_StorePendingBlob_Call) RunAndReturn(run func(ctx context.Context, userID uint, deviceID uint, streamID uint, blobInfo *stream.BlobInfo) error) *MockUploadService_StorePendingBlob_Call {
	_c.Call.Return(run)
	return _c
}

// StorePendingStream provides a mock function for the type MockUploadService
func (_mock *MockUploadService) StorePendingStream(ctx context.Context, userID uint, deviceID uint, sdBlob *stream.SDBlob, sdHash string) (uint, error) {
	ret := _mock.Called(ctx, userID, deviceID, sdBlob, sdHash)

	if len(ret) == 0 {
		panic("no return value specified for StorePendingStream")
	}

	var r0 uint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, *stream.SDBlob, string) (uint, error)); ok {
		return returnFunc(ctx, userID, deviceID, sdBlob, sdHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, *stream.SDBlob, string) uint); ok {
		r0 = returnFunc(ctx, userID, deviceID, sdBlob, sdHash)
	} else {
		r0 = ret.Get(0).(uint)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint, *stream.SDBlob, string) error); ok {
		r1 = returnFunc(ctx, userID, deviceID, sdBlob, sdHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_StorePendingStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorePendingStream'
type MockUploadService_StorePendingStream_Call struct {
	*mock.Call
}

// StorePendingStream is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - deviceID uint
//   - sdBlob *stream.SDBlob
//   - sdHash string
func (_e *MockUploadService_Expecter) StorePendingStream(ctx interface{}, userID interface{}, deviceID interface{}, sdBlob interface{}, sdHash interface{}) *MockUploadService_StorePendingStream_Call {
	return &MockUploadService_StorePendingStream_Call{Call: _e.mock.On("StorePendingStream", ctx, userID, deviceID, sdBlob, sdHash)}
}

func (_c *MockUploadService_StorePendingStream_Call) Run(run func(ctx context.Context, userID uint, deviceID uint, sdBlob *stream.SDBlob, sdHash string)) *MockUploadService_StorePendingStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 *stream.SDBlob
		if args[3] != nil {
			arg3 = args[3].(*stream.SDBlob)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUploadService_StorePendingStream_Call) Return(v uint, err error) *MockUploadService_StorePendingStream_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockUploadService_StorePendingStream_Call) RunAndReturn(run func(ctx context.Context, userID uint, deviceID uint, sdBlob *stream.SDBlob, sdHash string) (uint, error)) *MockUploadService_StorePendingStream_Call {
	_c.Call.Return(run)
	return _c
}
