// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/ipfs/go-cid"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/liblbry/stream"
	"go.lumeweb.com/portal-plugin-lbry/internal/db"
	"go.lumeweb.com/queryutil"
)

// NewMockUploadService creates a new instance of MockUploadService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUploadService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUploadService {
	mock := &MockUploadService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUploadService is an autogenerated mock type for the UploadService type
type MockUploadService struct {
	mock.Mock
}

type MockUploadService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUploadService) EXPECT() *MockUploadService_Expecter {
	return &MockUploadService_Expecter{mock: &_m.Mock}
}

// CreateStreamPin provides a mock function for the type MockUploadService
func (_mock *MockUploadService) CreateStreamPin(ctx context.Context, userId uint, sdCid cid.Cid) (*db.StreamPin, error) {
	ret := _mock.Called(ctx, userId, sdCid)

	if len(ret) == 0 {
		panic("no return value specified for CreateStreamPin")
	}

	var r0 *db.StreamPin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, cid.Cid) (*db.StreamPin, error)); ok {
		return returnFunc(ctx, userId, sdCid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, cid.Cid) *db.StreamPin); ok {
		r0 = returnFunc(ctx, userId, sdCid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.StreamPin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, cid.Cid) error); ok {
		r1 = returnFunc(ctx, userId, sdCid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_CreateStreamPin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStreamPin'
type MockUploadService_CreateStreamPin_Call struct {
	*mock.Call
}

// CreateStreamPin is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uint
//   - sdCid cid.Cid
func (_e *MockUploadService_Expecter) CreateStreamPin(ctx interface{}, userId interface{}, sdCid interface{}) *MockUploadService_CreateStreamPin_Call {
	return &MockUploadService_CreateStreamPin_Call{Call: _e.mock.On("CreateStreamPin", ctx, userId, sdCid)}
}

func (_c *MockUploadService_CreateStreamPin_Call) Run(run func(ctx context.Context, userId uint, sdCid cid.Cid)) *MockUploadService_CreateStreamPin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 cid.Cid
		if args[2] != nil {
			arg2 = args[2].(cid.Cid)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUploadService_CreateStreamPin_Call) Return(streamPin *db.StreamPin, err error) *MockUploadService_CreateStreamPin_Call {
	_c.Call.Return(streamPin, err)
	return _c
}

func (_c *MockUploadService_CreateStreamPin_Call) RunAndReturn(run func(ctx context.Context, userId uint, sdCid cid.Cid) (*db.StreamPin, error)) *MockUploadService_CreateStreamPin_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStream provides a mock function for the type MockUploadService
func (_mock *MockUploadService) DeleteStream(ctx context.Context, userID uint, sdHash string) error {
	ret := _mock.Called(ctx, userID, sdHash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStream")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = returnFunc(ctx, userID, sdHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUploadService_DeleteStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStream'
type MockUploadService_DeleteStream_Call struct {
	*mock.Call
}

// DeleteStream is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - sdHash string
func (_e *MockUploadService_Expecter) DeleteStream(ctx interface{}, userID interface{}, sdHash interface{}) *MockUploadService_DeleteStream_Call {
	return &MockUploadService_DeleteStream_Call{Call: _e.mock.On("DeleteStream", ctx, userID, sdHash)}
}

func (_c *MockUploadService_DeleteStream_Call) Run(run func(ctx context.Context, userID uint, sdHash string)) *MockUploadService_DeleteStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUploadService_DeleteStream_Call) Return(err error) *MockUploadService_DeleteStream_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUploadService_DeleteStream_Call) RunAndReturn(run func(ctx context.Context, userID uint, sdHash string) error) *MockUploadService_DeleteStream_Call {
	_c.Call.Return(run)
	return _c
}

// HandleUpload provides a mock function for the type MockUploadService
func (_mock *MockUploadService) HandleUpload(ctx context.Context, reader io.ReadSeekCloser) (cid.Cid, string, error) {
	ret := _mock.Called(ctx, reader)

	if len(ret) == 0 {
		panic("no return value specified for HandleUpload")
	}

	var r0 cid.Cid
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.ReadSeekCloser) (cid.Cid, string, error)); ok {
		return returnFunc(ctx, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.ReadSeekCloser) cid.Cid); ok {
		r0 = returnFunc(ctx, reader)
	} else {
		r0 = ret.Get(0).(cid.Cid)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.ReadSeekCloser) string); ok {
		r1 = returnFunc(ctx, reader)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, io.ReadSeekCloser) error); ok {
		r2 = returnFunc(ctx, reader)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUploadService_HandleUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleUpload'
type MockUploadService_HandleUpload_Call struct {
	*mock.Call
}

// HandleUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - reader io.ReadSeekCloser
func (_e *MockUploadService_Expecter) HandleUpload(ctx interface{}, reader interface{}) *MockUploadService_HandleUpload_Call {
	return &MockUploadService_HandleUpload_Call{Call: _e.mock.On("HandleUpload", ctx, reader)}
}

func (_c *MockUploadService_HandleUpload_Call) Run(run func(ctx context.Context, reader io.ReadSeekCloser)) *MockUploadService_HandleUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.ReadSeekCloser
		if args[1] != nil {
			arg1 = args[1].(io.ReadSeekCloser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadService_HandleUpload_Call) Return(cid1 cid.Cid, s string, err error) *MockUploadService_HandleUpload_Call {
	_c.Call.Return(cid1, s, err)
	return _c
}

func (_c *MockUploadService_HandleUpload_Call) RunAndReturn(run func(ctx context.Context, reader io.ReadSeekCloser) (cid.Cid, string, error)) *MockUploadService_HandleUpload_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockUploadService
func (_mock *MockUploadService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUploadService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockUploadService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockUploadService_Expecter) ID() *MockUploadService_ID_Call {
	return &MockUploadService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockUploadService_ID_Call) Run(run func()) *MockUploadService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUploadService_ID_Call) Return(s string) *MockUploadService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUploadService_ID_Call) RunAndReturn(run func() string) *MockUploadService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ListStreams provides a mock function for the type MockUploadService
func (_mock *MockUploadService) ListStreams(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*db.Stream, int64, error) {
	ret := _mock.Called(ctx, userID, filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListStreams")
	}

	var r0 []*db.Stream
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) ([]*db.Stream, int64, error)); ok {
		return returnFunc(ctx, userID, filters, sorts, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) []*db.Stream); ok {
		r0 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*db.Stream)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint, []queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(ctx, userID, filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUploadService_ListStreams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStreams'
type MockUploadService_ListStreams_Call struct {
	*mock.Call
}

// ListStreams is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - filters []queryutil.CrudFilter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockUploadService_Expecter) ListStreams(ctx interface{}, userID interface{}, filters interface{}, sorts interface{}, pagination interface{}) *MockUploadService_ListStreams_Call {
	return &MockUploadService_ListStreams_Call{Call: _e.mock.On("ListStreams", ctx, userID, filters, sorts, pagination)}
}

func (_c *MockUploadService_ListStreams_Call) Run(run func(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockUploadService_ListStreams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 []queryutil.CrudFilter
		if args[2] != nil {
			arg2 = args[2].([]queryutil.CrudFilter)
		}
		var arg3 []queryutil.Sort
		if args[3] != nil {
			arg3 = args[3].([]queryutil.Sort)
		}
		var arg4 queryutil.Pagination
		if args[4] != nil {
			arg4 = args[4].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUploadService_ListStreams_Call) Return(streams []*db.Stream, n int64, err error) *MockUploadService_ListStreams_Call {
	_c.Call.Return(streams, n, err)
	return _c
}

func (_c *MockUploadService_ListStreams_Call) RunAndReturn(run func(ctx context.Context, userID uint, filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]*db.Stream, int64, error)) *MockUploadService_ListStreams_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessUpload provides a mock function for the type MockUploadService
func (_mock *MockUploadService) ProcessUpload(ctx context.Context, result *stream.StreamResult, userId uint) error {
	ret := _mock.Called(ctx, result, userId)

	if len(ret) == 0 {
		panic("no return value specified for ProcessUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *stream.StreamResult, uint) error); ok {
		r0 = returnFunc(ctx, result, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUploadService_ProcessUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessUpload'
type MockUploadService_ProcessUpload_Call struct {
	*mock.Call
}

// ProcessUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - result *stream.StreamResult
//   - userId uint
func (_e *MockUploadService_Expecter) ProcessUpload(ctx interface{}, result interface{}, userId interface{}) *MockUploadService_ProcessUpload_Call {
	return &MockUploadService_ProcessUpload_Call{Call: _e.mock.On("ProcessUpload", ctx, result, userId)}
}

func (_c *MockUploadService_ProcessUpload_Call) Run(run func(ctx context.Context, result *stream.StreamResult, userId uint)) *MockUploadService_ProcessUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *stream.StreamResult
		if args[1] != nil {
			arg1 = args[1].(*stream.StreamResult)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUploadService_ProcessUpload_Call) Return(err error) *MockUploadService_ProcessUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUploadService_ProcessUpload_Call) RunAndReturn(run func(ctx context.Context, result *stream.StreamResult, userId uint) error) *MockUploadService_ProcessUpload_Call {
	_c.Call.Return(run)
	return _c
}
